// pet-system/pet-health-management/frontend/src/App.jsx
import { useState, useEffect } from 'react';
import PetSVG from './components/PetSVG';
import { petAPI, vaccinationAPI, checkupAPI, reminderAPI } from './services/api';
import './index.css';

function App() {
  const [pets, setPets] = useState([]);
  const [selectedPet, setSelectedPet] = useState(null);
  const [vaccinations, setVaccinations] = useState([]);
  const [checkups, setCheckups] = useState([]);
  const [reminders, setReminders] = useState([]);
  const [showAddPetModal, setShowAddPetModal] = useState(false);
  const [newPet, setNewPet] = useState({ name: '', type: 'dog', breed: '', birthday: '', weight: '' });

  useEffect(() => {
    loadPets();
    loadReminders();
  }, []);

  useEffect(() => {
    if (selectedPet) {
      loadVaccinations(selectedPet.id);
      loadCheckups(selectedPet.id);
    }
  }, [selectedPet]);

  const loadPets = async () => {
    try {
      const response = await petAPI.getAll();
      setPets(response.data);
    } catch (error) {
      console.error('Error loading pets:', error);
    }
  };

  const loadVaccinations = async (petId) => {
    try {
      const response = await vaccinationAPI.getByPet(petId);
      setVaccinations(response.data);
    } catch (error) {
      console.error('Error loading vaccinations:', error);
    }
  };

  const loadCheckups = async (petId) => {
    try {
      const response = await checkupAPI.getByPet(petId);
      setCheckups(response.data);
    } catch (error) {
      console.error('Error loading checkups:', error);
    }
  };

  const loadReminders = async () => {
    try {
      const response = await reminderAPI.getAll();
      setReminders(response.data);
    } catch (error) {
      console.error('Error loading reminders:', error);
    }
  };

  const handleAddPet = async (e) => {
    e.preventDefault();
    try {
      await petAPI.create(newPet);
      setShowAddPetModal(false);
      setNewPet({ name: '', type: 'dog', breed: '', birthday: '', weight: '' });
      loadPets();
    } catch (error) {
      console.error('Error adding pet:', error);
    }
  };

  const handleSelectPet = (pet) => {
    setSelectedPet(pet);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-blue-600 text-white p-4">
        <div className="container mx-auto">
          <h1 className="text-2xl font-bold">宠物健康管理工具</h1>
        </div>
      </nav>

      <div className="container mx-auto p-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="md:col-span-1">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-semibold">我的宠物</h2>
                <button
                  onClick={() => setShowAddPetModal(true)}
                  className="bg-blue-500 hover:bg-blue-600 text-white px-3 py-1 rounded"
                >
                  添加
                </button>
              </div>
              <div className="space-y-2">
                {pets.map((pet) => (
                  <div
                    key={pet.id}
                    onClick={() => handleSelectPet(pet)}
                    className={`p-3 rounded cursor-pointer ${
                      selectedPet?.id === pet.id ? 'bg-blue-100' : 'bg-gray-50 hover:bg-gray-100'
                    }`}
                  >
                    <div className="flex items-center">
                      <PetSVG type={pet.type} size={40} />
                      <span className="ml-2 font-medium">{pet.name}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="md:col-span-2">
            {selectedPet ? (
              <div className="bg-white rounded-lg shadow p-6">
                <div className="flex items-center mb-6">
                  <PetSVG type={selectedPet.type} size={120} />
                  <div className="ml-6">
                    <h2 className="text-2xl font-bold">{selectedPet.name}</h2>
                    <p className="text-gray-600">类型: {selectedPet.type === 'dog' ? '狗' : '猫'}</p>
                    {selectedPet.breed && <p className="text-gray-600">品种: {selectedPet.breed}</p>}
                    {selectedPet.birthday && <p className="text-gray-600">生日: {selectedPet.birthday}</p>}
                    {selectedPet.weight && <p className="text-gray-600">体重: {selectedPet.weight}kg</p>}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="text-lg font-semibold mb-3">疫苗记录</h3>
                    {/* Vaccine management will be implemented here */}
                    <div className="space-y-2">
                      {vaccinations.map((v) => (
                        <div key={v.id} className="bg-gray-50 p-2 rounded">
                          <p className="font-medium">{v.vaccine_name}</p>
                          <p className="text-sm text-gray-600">接种日期: {v.date_administered}</p>
                          {v.next_due_date && (
                            <p className="text-sm text-yellow-600">下次接种: {v.next_due_date}</p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h3 className="text-lg font-semibold mb-3">体检记录</h3>
                    {/* Checkup management will be implemented here */}
                    <div className="space-y-2">
                      {checkups.map((c) => (
                        <div key={c.id} className="bg-gray-50 p-2 rounded">
                          <p className="font-medium">体检日期: {c.checkup_date}</p>
                          <p className="text-sm text-gray-600">兽医: {c.vet_name}</p>
                          {c.weight && <p className="text-sm text-gray-600">体重: {c.weight}kg</p>}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-lg shadow p-6 text-center">
                <PetSVG type="dog" size={160} className="mx-auto mb-4" />
                <p className="text-gray-500 text-lg">请选择一个宠物查看详细信息</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {showAddPetModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
          <div className="bg-white rounded-lg p-6 w-96">
            <h2 className="text-xl font-bold mb-4">添加宠物</h2>
            <form onSubmit={handleAddPet} className="space-y-3">
              <input
                type="text"
                placeholder="宠物名字"
                value={newPet.name}
                onChange={(e) => setNewPet({ ...newPet, name: e.target.value })}
                className="w-full border px-3 py-2 rounded"
                required
              />
              <select
                value={newPet.type}
                onChange={(e) => setNewPet({ ...newPet, type: e.target.value })}
                className="w-full border px-3 py-2 rounded"
              >
                <option value="dog">狗</option>
                <option value="cat">猫</option>
              </select>
              <input
                type="text"
                placeholder="品种"
                value={newPet.breed}
                onChange={(e) => setNewPet({ ...newPet, breed: e.target.value })}
                className="w-full border px-3 py-2 rounded"
              />
              <input
                type="date"
                value={newPet.birthday}
                onChange={(e) => setNewPet({ ...newPet, birthday: e.target.value })}
                className="w-full border px-3 py-2 rounded"
              />
              <input
                type="number"
                step="0.1"
                placeholder="体重 (kg)"
                value={newPet.weight}
                onChange={(e) => setNewPet({ ...newPet, weight: e.target.value })}
                className="w-full border px-3 py-2 rounded"
              />
              <div className="flex justify-end space-x-2 mt-4">
                <button
                  type="button"
                  onClick={() => setShowAddPetModal(false)}
                  className="bg-gray-300 hover:bg-gray-400 px-4 py-2 rounded"
                >
                  取消
                </button>
                <button
                  type="submit"
                  className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
                >
                  添加
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;

// fit-system/frontend/src/App.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header -->
    <header class="bg-white shadow">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex items-center">
            <h1 class="text-xl font-bold text-gray-800">Fit System</h1>
          </div>
          <nav class="flex space-x-4">
            <button
              @click="activeTab = 'plans'"
              :class="['px-3 py-2 rounded-md text-sm font-medium', activeTab === 'plans' ? 'bg-blue-100 text-blue-700' : 'text-gray-500 hover:text-gray-700']"
            >
              训练计划
            </button>
            <button
              @click="activeTab = 'records'"
              :class="['px-3 py-2 rounded-md text-sm font-medium', activeTab === 'records' ? 'bg-blue-100 text-blue-700' : 'text-gray-500 hover:text-gray-700']"
            >
              训练记录
            </button>
            <button
              @click="activeTab = 'stats'"
              :class="['px-3 py-2 rounded-md text-sm font-medium', activeTab === 'stats' ? 'bg-blue-100 text-blue-700' : 'text-gray-500 hover:text-gray-700']"
            >
              统计分析
            </button>
          </nav>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div class="px-4 py-6 sm:px-0">
        <!-- Training Plans Tab -->
        <div v-if="activeTab === 'plans'">
          <h2 class="text-lg font-semibold mb-4">训练计划管理</h2>
          <button
            @click="showAddPlanModal = true"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4"
          >
            添加新计划
          </button>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div v-for="plan in plans" :key="plan.id" class="bg-white p-4 rounded shadow">
              <h3 class="font-semibold">{{ plan.name }}</h3>
              <p class="text-sm text-gray-600">{{ plan.description }}</p>
              <p class="text-sm">周期: {{ plan.duration_weeks }} 周</p>
              <p class="text-sm">强度: {{ plan.intensity_level }}/5</p>
            </div>
          </div>
        </div>

        <!-- Training Records Tab -->
        <div v-if="activeTab === 'records'">
          <h2 class="text-lg font-semibold mb-4">训练记录</h2>
          <button
            @click="showAddRecordModal = true"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4"
          >
            添加记录
          </button>
          <div class="space-y-4">
            <div v-for="record in records" :key="record.id" class="bg-white p-4 rounded shadow">
              <h3 class="font-semibold">训练日期: {{ record.training_date }}</h3>
              <p class="text-sm">表现评分: {{ record.performance_rating }}/5</p>
              <p class="text-sm">{{ record.notes }}</p>
            </div>
          </div>
        </div>

        <!-- Stats Tab -->
        <div v-if="activeTab === 'stats'">
          <h2 class="text-lg font-semibold mb-4">训练统计</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="bg-white p-4 rounded shadow">
              <h3 class="font-semibold">每周训练统计</h3>
              <div v-for="stat in weeklyStats" :key="stat.week_start">
                <p class="text-sm">{{ stat.week_start }}</p>
                <p class="text-sm">训练次数: {{ stat.training_sessions }}</p>
              </div>
            </div>
            <div class="bg-white p-4 rounded shadow">
              <h3 class="font-semibold">月度训练统计</h3>
              <div v-for="stat in monthlyStats" :key="stat.month_start">
                <p class="text-sm">{{ stat.month_start }}</p>
                <p class="text-sm">训练次数: {{ stat.training_sessions }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Add Plan Modal -->
    <div v-if="showAddPlanModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-xl w-96">
        <h3 class="text-lg font-semibold mb-4">添加新训练计划</h3>
        <form @submit.prevent="addPlan">
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">计划名称</label>
            <input v-model="newPlan.name" type="text" class="w-full px-3 py-2 border rounded" required>
          </div>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">描述</label>
            <textarea v-model="newPlan.description" class="w-full px-3 py-2 border rounded" rows="3"></textarea>
          </div>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">周期（周）</label>
            <input v-model.number="newPlan.duration_weeks" type="number" class="w-full px-3 py-2 border rounded" min="1" max="12" value="4">
          </div>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">强度级别（1-5）</label>
            <input v-model.number="newPlan.intensity_level" type="number" class="w-full px-3 py-2 border rounded" min="1" max="5" value="3">
          </div>
          <div class="flex space-x-2">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              添加
            </button>
            <button type="button" @click="showAddPlanModal = false" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
              取消
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Add Record Modal -->
    <div v-if="showAddRecordModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg shadow-xl w-96">
        <h3 class="text-lg font-semibold mb-4">添加训练记录</h3>
        <form @submit.prevent="addRecord">
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">选择训练计划</label>
            <select v-model="newRecord.plan_id" class="w-full px-3 py-2 border rounded" required>
              <option value="">请选择计划</option>
              <option v-for="plan in plans" :key="plan.id" :value="plan.id">{{ plan.name }}</option>
            </select>
          </div>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">训练日期</label>
            <input v-model="newRecord.training_date" type="date" class="w-full px-3 py-2 border rounded" required>
          </div>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">表现评分（1-5）</label>
            <input v-model.number="newRecord.performance_rating" type="number" class="w-full px-3 py-2 border rounded" min="1" max="5" required>
          </div>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-1">备注</label>
            <textarea v-model="newRecord.notes" class="w-full px-3 py-2 border rounded" rows="3"></textarea>
          </div>
          <div class="flex space-x-2">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              添加
            </button>
            <button type="button" @click="showAddRecordModal = false" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
              取消
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue';
import api from './services/api';

export default {
  name: 'App',
  setup() {
    const activeTab = ref('plans');
    const plans = ref([]);
    const records = ref([]);
    const weeklyStats = ref([]);
    const monthlyStats = ref([]);
    const showAddPlanModal = ref(false);
    const showAddRecordModal = ref(false);

    const newPlan = ref({
      name: '',
      description: '',
      duration_weeks: 4,
      intensity_level: 3,
      exercises: []
    });

    const newRecord = ref({
      plan_id: null,
      training_date: new Date().toISOString().split('T')[0],
      exercises: [],
      notes: '',
      performance_rating: 3
    });

    const fetchPlans = async () => {
      try {
        const response = await api.get('/plans');
        plans.value = response.data;
      } catch (error) {
        console.error('Error fetching plans:', error);
      }
    };

    const fetchRecords = async () => {
      try {
        const response = await api.get('/records');
        records.value = response.data;
      } catch (error) {
        console.error('Error fetching records:', error);
      }
    };

    const fetchWeeklyStats = async () => {
      try {
        const response = await api.get('/stats/weekly');
        weeklyStats.value = response.data;
      } catch (error) {
        console.error('Error fetching weekly stats:', error);
      }
    };

    const fetchMonthlyStats = async () => {
      try {
        const response = await api.get('/stats/monthly');
        monthlyStats.value = response.data;
      } catch (error) {
        console.error('Error fetching monthly stats:', error);
      }
    };

    const addPlan = async () => {
      try {
        await api.post('/plans', newPlan.value);
        showAddPlanModal.value = false;
        newPlan.value = {
          name: '',
          description: '',
          duration_weeks: 4,
          intensity_level: 3,
          exercises: []
        };
        fetchPlans();
      } catch (error) {
        console.error('Error adding plan:', error);
      }
    };

    const addRecord = async () => {
      try {
        await api.post('/records', newRecord.value);
        showAddRecordModal.value = false;
        newRecord.value = {
          plan_id: null,
          training_date: new Date().toISOString().split('T')[0],
          exercises: [],
          notes: '',
          performance_rating: 3
        };
        fetchRecords();
        fetchPlans();
        fetchWeeklyStats();
        fetchMonthlyStats();
      } catch (error) {
        console.error('Error adding record:', error);
      }
    };

    onMounted(() => {
      fetchPlans();
      fetchRecords();
      fetchWeeklyStats();
      fetchMonthlyStats();
    });

    return {
      activeTab,
      plans,
      records,
      weeklyStats,
      monthlyStats,
      showAddPlanModal,
      showAddRecordModal,
      newPlan,
      newRecord,
      addPlan,
      addRecord
    };
  }
};
</script>
